<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>shopping-cms-webapp</artifactId>
		<groupId>roosevelt.shopping</groupId>
		<version>3.0.2-SNAPSHOT</version>
	</parent>
	<groupId>roosevelt.shopping.modules</groupId>
	<artifactId>common-app</artifactId>
	<packaging>jar</packaging>
	<name>common-app Magnolia module</name>

	<properties>
		<magnoliaVersion>6.3.8</magnoliaVersion>
		<javaVersion>17</javaVersion>
		<powermock.version>1.7.1</powermock.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>info.magnolia</groupId>
			<artifactId>magnolia-core</artifactId>
			<version>${magnoliaVersion}</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.5</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>info.magnolia.rest</groupId>
			<artifactId>magnolia-rest-services</artifactId>
			<version>3.0.0</version>
			<!-- <exclusions> <exclusion> declare the exclusion here https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-client 
				<groupId>org.jboss.resteasy</groupId> <artifactId>resteasy-client</artifactId> 
				</exclusion> </exclusions> -->
		</dependency>
		<!-- https://mvnrepository.com/artifact/io.swagger/swagger-annotations -->
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>1.5.4</version>
		</dependency>

		<dependency>
			<groupId>info.magnolia.rest</groupId>
			<artifactId>magnolia-rest-integration</artifactId>
			<version>3.0.2</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.jboss.resteasy/resteasy-client -->




		<!-- TEST -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-module-junit4</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.powermock</groupId>
			<artifactId>powermock-api-mockito2</artifactId>
			<version>${powermock.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.sling</groupId>
			<artifactId>org.apache.sling.testing.jcr-mock</artifactId>
			<version>1.4.0</version>
			<scope>test</scope>
		</dependency>
	
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>${javaVersion}</source>
					<target>${javaVersion}</target>
				</configuration>
			</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <!-- Allow JUnit to access the test classes -->
         <argLine>
          -Xmx1024m -XX:MaxMetaspaceSize=256m
		  --add-opens java.base/java.util=ALL-UNNAMED 
          --add-opens java.base/java.lang=ALL-UNNAMED
          </argLine>     
        </configuration>
		</plugin>
		</plugins>

		<!-- default resources configuration which will filter the module descriptor -->
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<includes>
					<include>**/*</include>
				</includes>
			</resource>
			<resource>
				<filtering>true</filtering>
				<directory>src/main/resources</directory>
				<includes>
					<include>META-INF/magnolia/*</include>
				</includes>
			</resource>
		</resources>
	</build>

	<!-- <repositories> <repository> <id>magnolia.public</id> <url>https://nexus.magnolia-cms.com/content/groups/public</url> 
		<snapshots> </snapshots> </repository> </repositories> -->

</project>
